# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

# Triggers the workflow on push or pull request events (on every branch)
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: codecov/codecov-action@v1
      with:
        files: ./template_project/export/jacoco/test/jacocoTestReport.xml
    - name: Build the Docker image
      run: | 
        docker build -t registry.tech4comp.dbis.rwth-aachen.de/rwthacis/akg:${{ steps.extract_branch.outputs.branch }} .
    - name: Push to registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
        DOCKER_PW: ${{ secrets.DOCKER_PW }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PW registry.tech4comp.dbis.rwth-aachen.de
        docker push registry.tech4comp.dbis.rwth-aachen.de/rwthacis/akg:${{ steps.extract_branch.outputs.branch }}     
